name: vs-ponyc-latest

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  vs-ponyc-latest:
    name: Test against ponyc master
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-libressl:latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: make test ssl=0.9.0 config=debug
